//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerServiceWCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/ProvaWeek6.Core.Entity")]
    public partial class Client : object
    {
        
        private string ClientCodeField;
        
        private string FirstNameField;
        
        private int IdField;
        
        private string LastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCode
        {
            get
            {
                return this.ClientCodeField;
            }
            set
            {
                this.ClientCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/ProvaWeek6.Core.Entity")]
    public partial class Order : object
    {
        
        private decimal AmountField;
        
        private int ClientIdField;
        
        private int IdField;
        
        private string OrderCodeField;
        
        private System.DateTime OrderDateField;
        
        private string ProductCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderCode
        {
            get
            {
                return this.OrderCodeField;
            }
            set
            {
                this.OrderCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagerServiceWCF.IManagerService")]
    public interface IManagerService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/FetchClients", ReplyAction="http://tempuri.org/IManagerService/FetchClientsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ManagerServiceWCF.Client>> FetchClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/AddNewClient", ReplyAction="http://tempuri.org/IManagerService/AddNewClientResponse")]
        System.Threading.Tasks.Task<bool> AddNewClientAsync(ManagerServiceWCF.Client newClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/EditClient", ReplyAction="http://tempuri.org/IManagerService/EditClientResponse")]
        System.Threading.Tasks.Task<bool> EditClientAsync(ManagerServiceWCF.Client editedClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/DeleteClientById", ReplyAction="http://tempuri.org/IManagerService/DeleteClientByIdResponse")]
        System.Threading.Tasks.Task<bool> DeleteClientByIdAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/FetchOrdersPerClient", ReplyAction="http://tempuri.org/IManagerService/FetchOrdersPerClientResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ManagerServiceWCF.Order>> FetchOrdersPerClientAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/FetchDetailedOrderPerId", ReplyAction="http://tempuri.org/IManagerService/FetchDetailedOrderPerIdResponse")]
        System.Threading.Tasks.Task<ManagerServiceWCF.Order> FetchDetailedOrderPerIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IManagerServiceChannel : ManagerServiceWCF.IManagerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ManagerServiceClient : System.ServiceModel.ClientBase<ManagerServiceWCF.IManagerService>, ManagerServiceWCF.IManagerService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ManagerServiceClient() : 
                base(ManagerServiceClient.GetDefaultBinding(), ManagerServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IManagerService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ManagerServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ManagerServiceClient.GetBindingForEndpoint(endpointConfiguration), ManagerServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ManagerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ManagerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ManagerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ManagerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ManagerServiceWCF.Client>> FetchClientsAsync()
        {
            return base.Channel.FetchClientsAsync();
        }
        
        public System.Threading.Tasks.Task<bool> AddNewClientAsync(ManagerServiceWCF.Client newClient)
        {
            return base.Channel.AddNewClientAsync(newClient);
        }
        
        public System.Threading.Tasks.Task<bool> EditClientAsync(ManagerServiceWCF.Client editedClient)
        {
            return base.Channel.EditClientAsync(editedClient);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteClientByIdAsync(int clientId)
        {
            return base.Channel.DeleteClientByIdAsync(clientId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ManagerServiceWCF.Order>> FetchOrdersPerClientAsync(string clientCode)
        {
            return base.Channel.FetchOrdersPerClientAsync(clientCode);
        }
        
        public System.Threading.Tasks.Task<ManagerServiceWCF.Order> FetchDetailedOrderPerIdAsync(int id)
        {
            return base.Channel.FetchDetailedOrderPerIdAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IManagerService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IManagerService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/ProvaWeek6.WCF/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ManagerServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IManagerService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ManagerServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IManagerService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IManagerService,
        }
    }
}
